apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-ip-api-js
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-ip-api-js
  template:
    metadata:
      labels:
        app: log-ip-api-js
    spec:
      containers:
        - name: log-ip-api-js
          image: nonsochiagunye/log-ip-api-js
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: mysql-primary.db.svc.cluster.local
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: log-ip-api-js-secrets
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: log-ip-api-js-secrets
                  key: DB_PASS
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: log-ip-api-js-secrets
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: log-ip-api-js
  namespace: web
spec:
  type: NodePort
  selector:
    app: log-ip-api-js
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
